- name: timer
  notify:
    - restart docker-gc
  template:
    src: timer.j2
    dest: /etc/systemd/system/docker-gc.timer
  tags:
    - docker-gc

- name: service
  notify:
    - restart docker-gc
  template:
    src: service.j2
    dest: /etc/systemd/system/docker-gc.service
  tags:
    - docker-gc

- name: start
  systemd:
    name: docker-gc.timer
    state: started
    daemon_reload: yes
    masked: no
    enabled: yes
  tags:
    - docker-gc
