drone_server: drone/drone:0.8
drone_agent: drone/agent:0.8
drone_domain:
drone_debug: true
drone_open: true
drone_orgs:
drone_admins:
drone_max_procs: 2
drone_secret:

drone_github: false
drone_github_client:
drone_github_secret:

drone_gitea: false
drone_gitea_url:
drone_gitea_skip_verify: false
