- name: dirs
  with_items:
    - /compose/drone
  file:
    path: '{{ item }}'
    state: directory
  tags:
    - drone

- name: compose
  notify:
    - restart drone
  template:
    src: compose.j2
    dest: /compose/drone/docker-compose.yml
  tags:
    - drone

- name: default
  notify:
    - restart drone
  template:
    src: default.j2
    dest: /compose/drone/.env
  tags:
    - drone

- name: service
  notify:
    - restart drone
  template:
    src: service.j2
    dest: /etc/systemd/system/drone.service
  tags:
    - drone

- name: start
  systemd:
    name: drone
    state: started
    daemon_reload: yes
    masked: no
    enabled: yes
  tags:
    - drone
