- hosts: server
  gather_facts: False

  tasks:
    - name: bootstrap
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False

- hosts: server
  roles:
    - base
    - root
    - users
    - docker
    - docker-gc
    - traefik

- hosts: dchi
  roles:
    - drone
    - demo

- hosts: pangu
  roles:
    - drone
    - pages
    - downloads
    - lgtm
