- name: acme
  copy:
    content: ""
    dest: /etc/acme.json
    mode: u=rw,g=,o=
    force: no
  tags:
    - traefik

- name: config
  notify:
    - restart traefik
  template:
    src: config.j2
    dest: /etc/traefik.toml
  tags:
    - traefik

- name: dirs
  with_items:
    - /compose/traefik
  file:
    path: '{{ item }}'
    state: directory
  tags:
    - traefik

- name: compose
  notify:
    - restart traefik
  template:
    src: compose.j2
    dest: /compose/traefik/docker-compose.yml
  tags:
    - traefik

- name: default
  notify:
    - restart traefik
  template:
    src: default.j2
    dest: /compose/traefik/.env
  tags:
    - traefik

- name: service
  notify:
    - restart traefik
  template:
    src: service.j2
    dest: /etc/systemd/system/traefik.service
  tags:
    - traefik

- name: start
  systemd:
    name: traefik
    state: started
    daemon_reload: yes
    masked: no
    enabled: yes
  tags:
    - traefik
