- name: dirs
  with_items:
    - /compose/lgtm
  file:
    path: '{{ item }}'
    state: directory
  tags:
    - lgtm

- name: compose
  notify:
    - restart lgtm
  template:
    src: compose.j2
    dest: /compose/lgtm/docker-compose.yml
  tags:
    - lgtm

- name: default
  notify:
    - restart lgtm
  template:
    src: default.j2
    dest: /compose/lgtm/.env
  tags:
    - lgtm

- name: service
  notify:
    - restart lgtm
  template:
    src: service.j2
    dest: /etc/systemd/system/lgtm.service
  tags:
    - lgtm

- name: start
  systemd:
    name: lgtm
    state: started
    daemon_reload: yes
    masked: no
    enabled: yes
  tags:
    - lgtm
